vich_uploader:
    db_driver: orm

    mappings:
       about_images:
           uri_prefix: '%about_images%'
           upload_destination: '%kernel.project_dir%/public%about_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: false 
           delete_on_update: false
